name: CI

on: [push, pull_request]


jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go Deps
        run: |
          go mod tidy

  macosbuild:
    runs-on: macos-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go Deps
        run: |
          go mod tidy
  